/**
 * [D2] `app-map gen-configs` (05 §2, 06 R2): `.mcp.json` → `.cursor/mcp.json` + `.codex/config.toml`,
 * byte-for-byte golden strings, and `--check` drift detection.
 */
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { describe, it } from 'node:test';
import { GENERATED_FILES, codexTomlFromMcp, cursorConfigFromMcp, genConfigs, parseMcpJson } from '../gen-configs.ts';
import { REPO_ROOT } from './helpers.ts';

/** the committed `.mcp.json` of 05 §2 */
const PILOT_MCP_JSON = `{
  "mcpServers": {
    "app-map": {
      "command": "node",
      "args": ["\${CLAUDE_PROJECT_DIR:-.}/tools/app-map-mcp/dist/index.js"],
      "env": {
        "APP_MAP_DIR": "\${CLAUDE_PROJECT_DIR:-.}/app-map",
        "APP_MAP_PLATFORM": "\${APP_MAP_PLATFORM:-ios}",
        "APP_MAP_LOG_LEVEL": "\${APP_MAP_LOG_LEVEL:-info}"
      }
    },
    "argent": {
      "command": "npx",
      "args": ["-y", "@swmansion/argent@0.25.0"]
    }
  }
}
`;

const GOLDEN_CURSOR = `{
  "mcpServers": {
    "app-map": {
      "command": "node",
      "args": [
        "\${CLAUDE_PROJECT_DIR:-.}/tools/app-map-mcp/dist/index.js"
      ],
      "env": {
        "APP_MAP_DIR": "\${CLAUDE_PROJECT_DIR:-.}/app-map",
        "APP_MAP_PLATFORM": "\${APP_MAP_PLATFORM:-ios}",
        "APP_MAP_LOG_LEVEL": "\${APP_MAP_LOG_LEVEL:-info}"
      }
    },
    "argent": {
      "command": "npx",
      "args": [
        "-y",
        "@swmansion/argent@0.25.0"
      ]
    }
  }
}
`;

const GOLDEN_CODEX = `# Generated by \`app-map gen-configs\` from .mcp.json (05 §2) — do not edit.
# Codex expands \${VAR:-default} the same way Claude Code does, so placeholders are verbatim.

[mcp_servers.app-map]
command = "node"
args = ["\${CLAUDE_PROJECT_DIR:-.}/tools/app-map-mcp/dist/index.js"]

[mcp_servers.app-map.env]
APP_MAP_DIR = "\${CLAUDE_PROJECT_DIR:-.}/app-map"
APP_MAP_PLATFORM = "\${APP_MAP_PLATFORM:-ios}"
APP_MAP_LOG_LEVEL = "\${APP_MAP_LOG_LEVEL:-info}"

[mcp_servers.argent]
command = "npx"
args = ["-y", "@swmansion/argent@0.25.0"]
`;

function withRepo(mcpJson: string, fn: (root: string) => void): void {
  const root = mkdtempSync(join(tmpdir(), 'app-map-genconf-'));
  try {
    writeFileSync(join(root, '.mcp.json'), mcpJson);
    fn(root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

describe('generated content (05 §2)', () => {
  it('cursorConfigFromMcp is the same JSON object, 2 spaces + LF', () => {
    assert.equal(cursorConfigFromMcp(parseMcpJson(PILOT_MCP_JSON)), GOLDEN_CURSOR);
  });

  it('codexTomlFromMcp emits one [mcp_servers.<name>] table per server, in name order', () => {
    assert.equal(codexTomlFromMcp(parseMcpJson(PILOT_MCP_JSON)), GOLDEN_CODEX);
  });

  it('servers are ordered by name regardless of the .mcp.json order', () => {
    const reordered = parseMcpJson(JSON.stringify({
      mcpServers: {
        zulu: { command: 'node', args: ['z.js'] },
        alpha: { command: 'node', args: ['a.js'] },
      },
    }));
    assert.match(codexTomlFromMcp(reordered), /\[mcp_servers\.alpha\][\s\S]*\[mcp_servers\.zulu\]/);
    assert.match(cursorConfigFromMcp(reordered), /"alpha"[\s\S]*"zulu"/);
  });

  it('an http server keeps url and headers', () => {
    const toml = codexTomlFromMcp(parseMcpJson(JSON.stringify({
      mcpServers: { remote: { url: 'https://example.test/mcp', headers: { Authorization: '${MCP_TOKEN}' } } },
    })));
    assert.match(toml, /url = "https:\/\/example\.test\/mcp"/);
    assert.match(toml, /\[mcp_servers\.remote\.headers\]\nAuthorization = "\$\{MCP_TOKEN\}"/);
  });

  it('quotes and backslashes in values are TOML-escaped', () => {
    const toml = codexTomlFromMcp(parseMcpJson(JSON.stringify({
      mcpServers: { odd: { command: 'node', args: ['say "hi"', 'C:\\tools\\x'] } },
    })));
    assert.match(toml, /args = \["say \\"hi\\"", "C:\\\\tools\\\\x"\]/);
  });
});

describe('genConfigs writes and checks (06 R2)', () => {
  it('writes both files, then reports nothing left to write', () => {
    withRepo(PILOT_MCP_JSON, (root) => {
      const first = genConfigs(root);
      assert.deepEqual(first.written.slice().sort(), [GENERATED_FILES.codex, GENERATED_FILES.cursor].slice().sort());
      assert.ok(first.ok);
      assert.equal(readFileSync(join(root, GENERATED_FILES.cursor), 'utf8'), GOLDEN_CURSOR);
      assert.equal(readFileSync(join(root, GENERATED_FILES.codex), 'utf8'), GOLDEN_CODEX);
      assert.deepEqual(genConfigs(root).written, [], 'a second run is a no-op');
      assert.deepEqual(genConfigs(root, { check: true }), { written: [], stale: [], ok: true });
    });
  });

  it('--check reports an absent generated file as stale', () => {
    withRepo(PILOT_MCP_JSON, (root) => {
      const r = genConfigs(root, { check: true });
      assert.equal(r.ok, false);
      assert.deepEqual(r.stale.slice().sort(), [GENERATED_FILES.codex, GENERATED_FILES.cursor].slice().sort());
    });
  });

  it('--check detects a hand-edited generated file (byte-for-byte)', () => {
    withRepo(PILOT_MCP_JSON, (root) => {
      genConfigs(root);
      const codex = join(root, GENERATED_FILES.codex);
      writeFileSync(codex, `${readFileSync(codex, 'utf8')}\n# hand edit\n`);
      assert.deepEqual(genConfigs(root, { check: true }).stale, [GENERATED_FILES.codex]);
    });
  });

  it('--check detects drift after .mcp.json changes', () => {
    withRepo(PILOT_MCP_JSON, (root) => {
      genConfigs(root);
      writeFileSync(join(root, '.mcp.json'), PILOT_MCP_JSON.replace('0.25.0', '0.26.0'));
      const r = genConfigs(root, { check: true });
      assert.equal(r.ok, false);
      assert.equal(r.stale.length, 2);
    });
  });

  it('mkdir -p: the target directories need not exist', () => {
    withRepo(PILOT_MCP_JSON, (root) => {
      genConfigs(root);
      assert.ok(readFileSync(join(root, GENERATED_FILES.cursor), 'utf8').length > 0);
    });
  });

  it('a missing .mcp.json is not_found, not a crash', () => {
    const root = mkdtempSync(join(tmpdir(), 'app-map-genconf-'));
    try {
      assert.throws(() => genConfigs(root), /not found/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('the committed repo is in sync (the same check CI runs)', () => {
    assert.deepEqual(genConfigs(REPO_ROOT, { check: true }), { written: [], stale: [], ok: true });
  });

  it('an explicit mcpJsonPath is honoured', () => {
    withRepo('{"mcpServers":{}}', (root) => {
      const other = join(root, 'nested', 'mcp.json');
      mkdirSync(dirname(other), { recursive: true });
      writeFileSync(other, PILOT_MCP_JSON);
      genConfigs(root, { mcpJsonPath: other });
      assert.equal(readFileSync(join(root, GENERATED_FILES.codex), 'utf8'), GOLDEN_CODEX);
    });
  });
});

describe('parseMcpJson shape checks (bad_input)', () => {
  it('rejects malformed JSON, a missing mcpServers and bad field types', () => {
    assert.throws(() => parseMcpJson('{'), /not valid JSON/);
    assert.throws(() => parseMcpJson('[]'), /must be a JSON object/);
    assert.throws(() => parseMcpJson('{}'), /mcpServers/);
    assert.throws(() => parseMcpJson('{"mcpServers":{"x":[]}}'), /must be an object/);
    assert.throws(() => parseMcpJson('{"mcpServers":{"x":{}}}'), /command/);
    assert.throws(() => parseMcpJson('{"mcpServers":{"x":{"command":"node","args":"a"}}}'), /args/);
    assert.throws(() => parseMcpJson('{"mcpServers":{"x":{"command":"node","env":{"A":1}}}}'), /env\.A/);
  });

  it('accepts an empty server map', () => {
    assert.deepEqual(parseMcpJson('{"mcpServers":{}}'), { mcpServers: {} });
  });
});
