// Generated by scripts/app-map/gen-ids from app-map/ids.yaml — do not edit
// swiftlint:disable all
// Shared id registry (01 R1). App code references ids only through these constants;
// `app-map lint-ids` (01 R8) rejects string literals.

public enum AppMapID {
    /// Screen markers `screen.<screen_id>` for every screen root (01 R3).
    public enum Screen {
        public static let clientPicker = "screen.client_picker"
        public static let invoiceDetail = "screen.invoice_detail"
        public static let invoiceList = "screen.invoice_list"
        public static let invoiceNew = "screen.invoice_new"
        public static let login = "screen.login"
        public static let all: [String] = [clientPicker, invoiceDetail, invoiceList, invoiceNew, login]
    }

    /// Element identifiers for every interactive element and form label (01 R4).
    public enum Element {
        public static let clientPickerCancelButton = "client.picker.cancel.button" // button
        public static let clientPickerCell = "client.picker.cell" // cell; dynamic
        public static let clientPickerList = "client.picker.list" // list; dynamic
        public static let clientPickerSearchField = "client.picker.search.field" // field
        public static let invoiceAddButton = "invoice.add.button" // button
        public static let invoiceAmountField = "invoice.amount.field" // field
        public static let invoiceCancelButton = "invoice.cancel.button" // button
        public static let invoiceClientPicker = "invoice.client.picker" // picker
        public static let invoiceDetailAmountText = "invoice.detail.amount.text" // text; dynamic
        public static let invoiceDetailBackButton = "invoice.detail.back.button" // button
        public static let invoiceDetailClientText = "invoice.detail.client.text" // text; dynamic
        public static let invoiceDetailEditButton = "invoice.detail.edit.button" // button
        public static let invoiceDetailItemCell = "invoice.detail.item.cell" // cell; dynamic
        public static let invoiceDetailItemsList = "invoice.detail.items.list" // list; dynamic
        public static let invoiceDetailSendButton = "invoice.detail.send.button" // button; intent_critical
        public static let invoiceDetailStatusText = "invoice.detail.status.text" // text; dynamic
        public static let invoiceDuePicker = "invoice.due.picker" // picker
        public static let invoiceFilterButton = "invoice.filter.button" // button
        public static let invoiceListCell = "invoice.list.cell" // cell; dynamic
        public static let invoiceListCollection = "invoice.list.collection" // list; dynamic
        public static let invoiceListTable = "invoice.list.table" // list; dynamic
        public static let invoiceNoteField = "invoice.note.field" // field
        public static let invoiceSaveButton = "invoice.save.button" // button; intent_critical
        public static let loginBiometricButton = "login.biometric.button" // button
        public static let loginEmailField = "login.email.field" // field
        public static let loginErrorText = "login.error.text" // text; dynamic
        public static let loginForgotLink = "login.forgot.link" // link
        public static let loginPasswordField = "login.password.field" // field
        public static let loginSubmitButton = "login.submit.button" // button
        public static let navClientsTab = "nav.clients.tab" // tab
        public static let navInvoicesTab = "nav.invoices.tab" // tab
        public static let navSettingsTab = "nav.settings.tab" // tab
        public static let all: [String] = [clientPickerCancelButton, clientPickerCell, clientPickerList, clientPickerSearchField, invoiceAddButton, invoiceAmountField, invoiceCancelButton, invoiceClientPicker, invoiceDetailAmountText, invoiceDetailBackButton, invoiceDetailClientText, invoiceDetailEditButton, invoiceDetailItemCell, invoiceDetailItemsList, invoiceDetailSendButton, invoiceDetailStatusText, invoiceDuePicker, invoiceFilterButton, invoiceListCell, invoiceListCollection, invoiceListTable, invoiceNoteField, invoiceSaveButton, loginBiometricButton, loginEmailField, loginErrorText, loginForgotLink, loginPasswordField, loginSubmitButton, navClientsTab, navInvoicesTab, navSettingsTab]
    }

    /// Gate markers for interrupters (01 R7) and their dismiss controls.
    public enum Gate {
        public static let biometricPrompt = "gate.biometric_prompt"
        public static let pushPermission = "gate.push_permission"
        public static let all: [String] = [biometricPrompt, pushPermission]

        public enum Dismiss {
            public static let biometricPromptCancel = "gate.biometric_prompt.cancel"
            public static let pushPermissionDeny = "gate.push_permission.deny"
            public static let all: [String] = [biometricPromptCancel, pushPermissionDeny]
        }
    }
}
