/**
 * [D2] `app-map gen-configs [--check]` (05 §2, 06 R2): derive `.cursor/mcp.json` and
 * `.codex/config.toml` from the committed `.mcp.json`.
 *
 * - `.cursor/mcp.json`: the same JSON object (`mcpServers` key), pretty-printed 2 spaces + LF.
 * - `.codex/config.toml`: one `[mcp_servers.<name>]` table per server with `command`, `args`
 *   (TOML array) and `[mcp_servers.<name>.env]` for `env`; `${VAR:-default}` placeholders are
 *   copied verbatim (Codex expands them the same way); servers in name order; LF.
 * - `--check`: regenerate to memory and compare byte-for-byte; `stale` lists mismatches and the
 *   CLI exits 1 (06 R2).
 * Never writes secrets: `.mcp.json` must contain only `${VAR}` references (policy-check.ts).
 *
 * Layer: top (imports errors/types only).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { GenConfigsResult } from './types.ts';
import { AppMapError, ERROR_CODES } from './errors.ts';

export interface McpJson {
  mcpServers: Record<string, { command: string; args?: string[]; env?: Record<string, string>; url?: string; headers?: Record<string, string> }>;
}

export const GENERATED_FILES = { cursor: '.cursor/mcp.json', codex: '.codex/config.toml' } as const;

/** Header of the generated TOML; stable (no timestamps) so `--check` can compare byte-for-byte. */
const CODEX_HEADER = [
  '# Generated by `app-map gen-configs` from .mcp.json (05 §2) — do not edit.',
  '# Codex expands ${VAR:-default} the same way Claude Code does, so placeholders are verbatim.',
].join('\n');

export function genConfigs(repoRoot: string, opts: { check?: boolean; mcpJsonPath?: string } = {}): GenConfigsResult {
  const mcpPath = opts.mcpJsonPath ?? join(repoRoot, '.mcp.json');
  if (!existsSync(mcpPath)) {
    throw new AppMapError(ERROR_CODES.NOT_FOUND, `${mcpPath} not found`, 'gen-configs derives the Cursor/Codex configs from the committed .mcp.json (05 §2)');
  }
  const mcp = parseMcpJson(readFileSync(mcpPath, 'utf8'));
  const targets: Array<{ rel: string; text: string }> = [
    { rel: GENERATED_FILES.cursor, text: cursorConfigFromMcp(mcp) },
    { rel: GENERATED_FILES.codex, text: codexTomlFromMcp(mcp) },
  ];
  if (opts.check === true) {
    // 06 R2: byte-for-byte; an absent generated file is stale, not an error.
    const stale = targets.filter((t) => readIfPresent(join(repoRoot, t.rel)) !== t.text).map((t) => t.rel);
    return { written: [], stale, ok: stale.length === 0 };
  }
  const written: string[] = [];
  for (const t of targets) {
    const abs = join(repoRoot, t.rel);
    if (readIfPresent(abs) === t.text) continue;
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, t.text, 'utf8');
    written.push(t.rel);
  }
  return { written, stale: [], ok: true };
}

function readIfPresent(path: string): string | undefined {
  return existsSync(path) ? readFileSync(path, 'utf8') : undefined;
}

/** Pure. */
export function cursorConfigFromMcp(mcp: McpJson): string {
  // Same object, same key order as `.mcp.json` (05 §2 "same JSON, `mcpServers` key"); LF + trailing newline.
  const servers: McpJson['mcpServers'] = {};
  for (const name of sortedNames(mcp)) servers[name] = mcp.mcpServers[name]!;
  return `${JSON.stringify({ mcpServers: servers }, null, 2).replace(/\r\n/g, '\n')}\n`;
}

/** Pure. */
export function codexTomlFromMcp(mcp: McpJson): string {
  const out: string[] = [CODEX_HEADER];
  for (const name of sortedNames(mcp)) {
    const s = mcp.mcpServers[name]!;
    const table = `mcp_servers.${tomlKey(name)}`;
    out.push('', `[${table}]`);
    if (s.command !== undefined) out.push(`command = ${tomlString(s.command)}`);
    if (s.args !== undefined) out.push(`args = ${tomlArray(s.args)}`);
    if (s.url !== undefined) out.push(`url = ${tomlString(s.url)}`);
    if (s.env !== undefined && Object.keys(s.env).length > 0) {
      out.push('', `[${table}.env]`);
      for (const [k, v] of Object.entries(s.env)) out.push(`${tomlKey(k)} = ${tomlString(v)}`);
    }
    if (s.headers !== undefined && Object.keys(s.headers).length > 0) {
      out.push('', `[${table}.headers]`);
      for (const [k, v] of Object.entries(s.headers)) out.push(`${tomlKey(k)} = ${tomlString(v)}`);
    }
  }
  return `${out.join('\n')}\n`;
}

/** servers in name order (05 §2: a stable order so `--check` never flaps) */
function sortedNames(mcp: McpJson): string[] {
  return Object.keys(mcp.mcpServers).sort();
}

/** TOML bare key when possible (`A-Za-z0-9_-`), quoted otherwise. */
function tomlKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : tomlString(key);
}

function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

function tomlArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(', ')}]`;
}

/** Pure: parse + shape-check `.mcp.json` (throws `bad_input`). */
export function parseMcpJson(text: string): McpJson {
  let doc: unknown;
  try {
    doc = JSON.parse(text);
  } catch (e) {
    throw new AppMapError(ERROR_CODES.BAD_INPUT, `.mcp.json is not valid JSON: ${(e as Error).message}`, 'fix the JSON syntax');
  }
  if (typeof doc !== 'object' || doc === null || Array.isArray(doc)) {
    throw new AppMapError(ERROR_CODES.BAD_INPUT, '.mcp.json must be a JSON object', 'the top level is `{"mcpServers": {…}}` (05 §2)');
  }
  const raw = (doc as { mcpServers?: unknown }).mcpServers;
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    throw new AppMapError(ERROR_CODES.BAD_INPUT, '.mcp.json needs an `mcpServers` object', 'see 05 §2 for the shape');
  }
  const servers: McpJson['mcpServers'] = {};
  for (const [name, value] of Object.entries(raw as Record<string, unknown>)) {
    if (typeof value !== 'object' || value === null || Array.isArray(value)) {
      throw new AppMapError(ERROR_CODES.BAD_INPUT, `mcpServers.${name} must be an object`, 'each server is `{command, args?, env?}` or `{url, headers?}`');
    }
    const v = value as Record<string, unknown>;
    const server: McpJson['mcpServers'][string] = { command: '' };
    if (v.command !== undefined) {
      if (typeof v.command !== 'string') throw badField(name, 'command', 'a string');
      server.command = v.command;
    } else if (typeof v.url === 'string') {
      // http transport: no command
      delete (server as { command?: string }).command;
    } else {
      throw badField(name, 'command', 'a string (or give `url` for an http server)');
    }
    if (v.args !== undefined) {
      if (!Array.isArray(v.args) || v.args.some((a) => typeof a !== 'string')) throw badField(name, 'args', 'an array of strings');
      server.args = v.args as string[];
    }
    if (v.env !== undefined) server.env = stringMap(name, 'env', v.env);
    if (v.headers !== undefined) server.headers = stringMap(name, 'headers', v.headers);
    if (v.url !== undefined) {
      if (typeof v.url !== 'string') throw badField(name, 'url', 'a string');
      server.url = v.url;
    }
    servers[name] = server;
  }
  return { mcpServers: servers };
}

function badField(server: string, field: string, expected: string): AppMapError {
  return new AppMapError(ERROR_CODES.BAD_INPUT, `mcpServers.${server}.${field} must be ${expected}`, 'see 05 §2 for the .mcp.json shape');
}

function stringMap(server: string, field: string, value: unknown): Record<string, string> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw badField(server, field, 'an object of strings');
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
    if (typeof v !== 'string') throw badField(server, `${field}.${k}`, 'a string');
    out[k] = v;
  }
  return out;
}
